import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Nav from '../components/navbar'
import Footer from '../components/footer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Nav />
        {children}
        <Footer/>
        </body>
    </html>
  )
}
